
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

    using System;

    public partial class Market
    {
        public string ID { get; set; }

        public string IconUrl { get; set; }

        public string Name { get; set; }

        public string SmsUrl { get; set; }

        public int MaxMoney { get; set; }

        public string Tenure { get; set; }

        public string Rate { get; set; }

        public string ApprovlTime { get; set; }

        public string Disbursement { get; set; }

        public int SortId { get; set; }

        public Nullable<System.DateTime> CreateTime { get; set; }

        public string CreatePerson { get; set; }

        public Nullable<System.DateTime> UpdateTime { get; set; }

        public string UpdatePerson { get; set; }

        public int State { get; set; }
    }
}
