//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class Orders
    {
        public string OrderId { get; set; }
        public string PulsaCode { get; set; }
        public string CnPulsatype { get; set; }
        public string Masaaktif { get; set; }
        public string CnQuatity { get; set; }
        public string CnOp { get; set; }
        public decimal UsePoints { get; set; }
        public decimal CnPrice { get; set; }
        public decimal CnOldprice { get; set; }
        public string OperatorName { get; set; }
        public int WechatpayState { get; set; }
        public int PulsaState { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string WechatOpenid { get; set; }
        public string WechatNickname { get; set; }
    }
}
