//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class UserPoints
    {
        public string ID { get; set; }
        public string OrderId { get; set; }
        public decimal Point { get; set; }
        public string ToOpenid { get; set; }
        public string FromWechatOpenid { get; set; }
        public string FromWechatNickname { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Status { get; set; }
    }
}
