//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class WeChatUser
    {
        public string OpenId { get; set; }
        public string Nickname { get; set; }
        public int Sex { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Headimgurl { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
